behaviors:
  ChasersBehaviour:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 5
    max_steps: 5000000
    summary_freq: 500
    threaded: true
    network_settings:
      num_layers: 3
      hidden_units: 32
  RunnersBehaviour:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 5
    max_steps: 5000000
    summary_freq: 500
    threaded: true
    network_settings:
      num_layers: 3
      hidden_units: 32